debug: false
log_level: INFO
telemetry_disabled: true

storage:
  storage_path: qdrant/storage
  snapshots_path: qdrant/storage

service:
  host: 0.0.0.0
  http_port: 6333
  # Uncomment to enable gRPC:
  grpc_port: 6334
