version: '3'
services:
  qdrant:
    image: "qdrant/qdrant"
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
  bloop-app:
    image: bloop-app
    restart: on-failure
    command: --qdrant-url=http://qdrant:6334
    depends_on:
      qdrant:
        condition: service_started
    ports:
      - "7878:7878"
    expose:
      - 7878
    build:
      dockerfile: "./Dockerfile"
      args:
        - OPENAI_API_KEY
        - GITHUB_ACCESS_TOKEN