apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bloop.fullname" . }}-storage
  labels:
    app: {{ template "bloop.name" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}