apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bloop.fullname" . }}
  labels:
    {{- include "bloop.labels" . | nindent 4 }}
type: Opaque
data:
  github-app-private-key.pem: {{ .Values.bloop.githubAppPrivateKey | b64enc }}