apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bloop.fullname" . }}-proxy-config
data:
  Caddyfile: |
    :8080

    reverse_proxy * {
      to localhost:7878
    }
    basicauth /* {
      {{ .Values.proxy.user }} {{ .Values.proxy.passwordHash }}
    }
