apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qdrant.fullname" . }}
data:
  initialize.sh: |
    #!/bin/sh
    SET_INDEX=${HOSTNAME##*-}
    {{- if and (.Values.qdrant.snapshotRestoration.enabled) (eq (.Values.qdrant.replicaCount | quote)  (1 | quote)) }}
    echo "Starting initializing for pod $SET_INDEX and snapshots restoration"
    ./qdrant {{ range .Values.qdrant.snapshotRestoration.snapshots }} --snapshot {{ . }} {{ end }}
    {{- else }}
    echo "Starting initializing for pod $SET_INDEX"
    if [ "$SET_INDEX" = "0" ]; then
      ./qdrant --uri 'http://{{ include "bloop.fullname" . }}-qdrant-0.{{ include "bloop.fullname" . }}-qdrant-headless:6335' --storage-snapshot '{{ .Values.qdrant.snapshot.path }}'
    else
      ./qdrant --bootstrap 'http://{{ include "bloop.fullname" . }}-qdrant-0.{{ include "bloop.fullname" . }}-qdrant-headless:6335' --uri 'http://{{ include "bloop.fullname" . }}-qdrant-'"$SET_INDEX"'.{{ include "bloop.fullname" . }}-qdrant-headless:6335' --storage-snapshot '{{ .Values.qdrant.snapshot.path }}'
    fi
    {{ end }}
  production.yaml: |
    {{- toYaml .Values.qdrant.config | nindent 4 }}