apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qdrant.fullname" . }}-storage
  labels:
    app: {{ template "qdrant.name" . }}
spec:
  storageClassName: {{ .Values.qdrant.persistence.storageClassName }}
  accessModes:
  {{- range .Values.qdrant.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size | quote }}