{{ if .Values.qdrant.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant.fullname" . }}-backup
type: Opaque
data:
  aws-access-key-id: {{ .Values.qdrant.backup.awsAccessKey | b64enc }}
  aws-secret-access-key: {{ .Values.qdrant.backup.awsSecretAccessKey | b64enc }}
{{ end -}}
