apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qdrant.fullname" . }}
data:
  initialize.sh: |
    #!/bin/sh
    SET_INDEX=${HOSTNAME##*-}
    {{- if and (.Values.qdrant.restore.enabled) (eq (.Values.qdrant.replicaCount | quote)  (1 | quote)) }}
    echo "Starting initializing for pod $SET_INDEX and snapshots restoration"
    ./qdrant --snapshot {{ .Values.qdrant.config.storage.snapshots_path }}/restore.snapshot:documents
    {{- else }}
    echo "Starting initializing for pod $SET_INDEX"
    if [ "$SET_INDEX" = "0" ]; then
      ./qdrant --uri 'http://{{ include "bloop.fullname" . }}-qdrant-0.{{ include "bloop.fullname" . }}-qdrant-headless:6335'
    else
      ./qdrant --bootstrap 'http://{{ include "bloop.fullname" . }}-qdrant-0.{{ include "bloop.fullname" . }}-qdrant-headless:6335' --uri 'http://{{ include "bloop.fullname" . }}-qdrant-'"$SET_INDEX"'.{{ include "bloop.fullname" . }}-qdrant-headless:6335'
    fi
    {{ end }}
  production.yaml: |
    {{- toYaml .Values.qdrant.config | nindent 4 }}