apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .Values.service.annotations) . | indent 4 }}
{{- end }}
  name: {{ include "bloop.fullname" . }}
  labels:
    {{- include "bloop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 7878
  selector:
    {{- include "bloop.selectorLabels" . | nindent 4 }}
