name: Build&Push API docker container image with SHA tag
on: push

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          sudo apt install git-lfs
          git lfs pull

  build_and_push:
    needs: [install_dependencies]
    uses: BloopAI/workflows/.github/workflows/build-container.yml@main
    with:
      repository: bloop
      tag: build-${{ github.sha }}
    secrets:
      awsRegion: eu-west-1
      awsAccountID: '466687392010'
      slackBuildWebhook: ${{ secrets.SLACK_BUILD_WEBHOOK }}

  validate_helm:
    uses: BloopAI/reusable-workflows/.github/workflows/validate-helm-chart.yml@main
    with:
      path: helm/bloop
    secrets:
      slackBuildWebhook: ${{ secrets.SLACK_BUILD_WEBHOOK }}
