name: Build Bloop container with latest PR commit tag on build command

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run:   echo "$GITHUB_CONTEXT"
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}

  build_tag:
    runs-on: ubuntu-latest
    name: Run container build on comment
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build')
    outputs:
      tag: build-${{ steps.comment-branch.outputs.head_sha }}
      ref: ${{ steps.comment-branch.outputs.head_ref }}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

  build_and_push:
    uses: BloopAI/workflows/.github/workflows/build-container.yml@main
    needs: [build_tag]
    with:
      repository: bloop
      tag: ${{ needs.build_tag.outputs.tag }}
      runner: docker
    secrets:
      awsRegion: ${{ secrets.AWS_REGION }}
      awsAccountID: ${{ secrets.AWS_ACCOUNT_ID }}
      slackBuildWebhook: ${{ secrets.SLACK_BUILD_WEBHOOK }}

  report_status:
    runs-on: ubuntu-latest
    name: Report status of the build
    if: always()
    needs: [build_tag, build_and_push]
    steps:
      - name: pr
        id: pr
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "number=${PR_NUMBER}" >> ${GITHUB_OUTPUT}

      - name: Comment failure build
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :red_circle: Bloop container with `${{ needs.build_tag.outputs.tag }}` tag failed!
            :link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          pr_number: ${{ steps.pr.outputs.number }}

      - name: Comment success build
        if: ${{ !contains(needs.*.result, 'failure') }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :green_circle: Bloop container with `${{ needs.build_tag.outputs.tag }}` tag is ready!
            :link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          pr_number: ${{ steps.pr.outputs.number }}
