name: Dependency matrix	

on:	
  workflow_dispatch:
  pull_request:	
    branches: [main]	
    paths:	
      - "flake.nix"	
      - "flake.lock"	
      - ".github/workflows/dependencies.yml"	

jobs:	
  qdrant-rustup:	
    strategy:	
      fail-fast: false	
      matrix:	
        package: [ qdrant ]	
        target: [	
          x86_64-unknown-linux-gnu,	
          x86_64-apple-darwin,	
          aarch64-apple-darwin,	
          x86_64-pc-windows-msvc
        ]	

        include:	
          - target: x86_64-unknown-linux-gnu	
            os: ubuntu-latest	
            cross: false	

          - target: x86_64-apple-darwin	
            os: macos-11	
            cross: false	

          - target: aarch64-apple-darwin	
            os: macos-11	
            cross: true
            
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false

    runs-on: ${{ matrix.os }}	
    steps:	
      - name: Install Rust stable	
        uses: dtolnay/rust-toolchain@stable
        with:	
          toolchain: stable	
          target: ${{ matrix.target }}	

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build qdrant	
        env:	
          VERSION: 1.5.1
        run: |	
          cargo install --target ${{ matrix.target }} --git https://github.com/qdrant/qdrant --tag v${{ env.VERSION }} --locked --root . qdrant	
      - name: Upload binaries	
        uses: actions/upload-artifact@v3	
        with:	
          name: "${{ matrix.package }}_${{ matrix.target }}"	
          path: bin	
