name: Tauri Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, semantic]
    paths:
      - "apps/desktop/**"
      - ".github/workflows/tauri**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No checks required" '
  fmt-clippy-build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No checks required" '
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No checks required" '

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - uses: Swatinem/rust-cache@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Formatting
        run: |
          cargo fmt -p bloop -- --check

      - name: Run tests
        run: |
          cargo test -p bloop --verbose

      - uses: actions-rs/clippy-check@v1
        with:
          toolchain: stable
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p app --all-features --manifest-path Cargo.toml
