name: Tauri Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "apps/desktop/**"
      - ".github/workflows/tauri**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.73.0
          components: rustfmt, clippy

      - name: Install Tauri deps
        run: | 
              sudo apt update && \
              sudo apt install libwebkit2gtk-4.0-dev \
                build-essential \
                curl \
                wget \
                file \
                libssl-dev \
                libgtk-3-dev \
                libayatana-appindicator3-dev \
                librsvg2-dev

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Rustfmt
        run: cargo --locked fmt -p bloop -- --check

      - name: Clippy
        run: cargo --locked clippy -p bloop

      - name: Tests
        run: cargo --locked test -p bloop --release