name: Tauri Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "apps/desktop/**"
      - ".github/workflows/tauri**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable cachix
        uses: cachix/cachix-action@v12
        with:
          name: bloopai
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Rustfmt
        run: nix develop -c bash -c 'cargo --locked fmt -p bloop -- --check'

      - name: Clippy
        run: nix develop -c bash -c 'cargo --locked clippy -p bloop'

      - name: Tests
        run: nix develop -c bash -c 'cargo --locked test -p bloop --release'

      - name: Sccache stats
        run: nix develop -c bash -c 'sccache --show-stats'
